---
abstract: 'Perl extension for Berkeley DB version 2, 3, 4 or 5'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BerkeleyDB
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.56'
